apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
    - image: kris2111/auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: kris2111/client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: kris2111/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
    - image: kris2111/orders
      context: orders
      docker:
        dockerfile: Dockerfile
    - image: kris2111/payments
      context: payments
      docker:
        dockerfile: Dockerfile    
    - image: kris2111/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile    

manifests:
  rawYaml:
    # - infra/k8s/auth-depl.yaml
    # - infra/k8s/ingress-srv.yaml
    # - infra/k8s/auth-mongo-depl.yaml
    # - infra/k8s/client-depl.yaml
    # - infra/k8s/tickets-depl.yaml
    # - infra/k8s/tickets-mongo-depl.yaml
    # - infra/k8s/nats-depl.yaml
    - infra/k8s/*
